;; Generated by kunagi-toolbox.

(ns dls.appinfo)

(def
 appinfo
 {:browserapp {:js-optimizations :simple},
  :build-time "2020-04-24 11:19",
  :legal {:datenschutzerklaerung-bausteine [:vertragsabwicklung
                                            :serverdaten
                                            :cookies
                                            :kontaktanfragen],
          :vendor "Frankenburg Softwaretechnik GmbH\nUnter der Frankenburg 20, 31737 Rinteln\nGeschäftsführer Fabian Hager und Witoslaw Koczewski\nAmtsgericht Stadthagen HRB 201547\nUmsatzsteuer-ID DE322317556\nTelefon +49 5751 9934900\nE-Mail mail@frankenburg.software"},
  :project {:group "kunagi", :id "dls", :name "Datalog Server"},
  :release {:major 1, :minor 0},
  :serverapp {:config-dir "/etc/dls",
              :executable-name "dlsd",
              :executable-path "/usr/local/bin/dlsd",
              :http-port 23010,
              :uri "https://dls.frankenburg.software",
              :user-name "dls",
              :vhost "dls.frankenburg.software",
              :working-dir "/var/local/dls"}})
